# ============================================
# Hexo 博客配置文件
# 官方文档: https://hexo.io/docs/configuration.html
# 源码地址: https://github.com/hexojs/hexo/
# ============================================

# ============================================
# 网站基本信息配置
# ============================================
title: TJU SEIE Lab-418 Blog          # 网站标题，显示在浏览器标签页和网站头部
subtitle: ''                          # 网站副标题，可留空或填写简短描述
description: '嵌入式技术分享'          # 网站描述，用于SEO优化，显示在搜索结果中
keywords: ''   # 网站关键词，多个关键词用逗号分隔，有助于SEO
author: LJC                           # 作者名称，显示在文章页面和版权信息中
language: zh-CN                       # 网站语言 (zh-CN中文, en英文, ja日文等)
timezone: 'Asia/Shanghai'             # 时区设置，影响文章发布时间显示

# ============================================
# URL 和路径配置
# ============================================
# 网站URL配置，根据部署方式选择合适的配置
# url: http://154.8.222.175             # 网站访问地址，部署时需要修改为实际域名或IP
# root: /                               # 网站根目录，如果部署在子目录下需要修改
# GitHub Pages 示例配置:
url: https://cloak1522.github.io/418blog
root: /418blog/

# 文章链接格式配置
permalink: :year/:month/:category/:title/  # 文章URL格式 (:year年份 :month月份 :day日期 :title标题)
# 其他格式示例:
# permalink: :title/                  # 仅标题
# permalink: posts/:title/            # posts/标题
# permalink: :category/:title/        # 分类/标题
permalink_defaults:                   # 默认值，当某些变量为空时使用
  lang: zh                           # 默认语言
  category: uncategorized            # 默认分类

# 美化URL配置
pretty_urls:
  trailing_index: false               # 是否保留末尾的 index.html (true保留, false移除)
  trailing_html: false                # 是否保留末尾的 .html (true保留, false移除)

# ============================================
# 目录结构配置
# ============================================
source_dir: source                   # 源文件目录，存放Markdown文件和静态资源
public_dir: public                   # 生成的静态文件目录，部署时上传此目录
tag_dir: tags                        # 标签页面目录
archive_dir: archives               # 归档页面目录
category_dir: categories            # 分类页面目录
code_dir: downloads/code             # 代码下载目录
i18n_dir: :lang                      # 多语言目录
skip_render:                         # 跳过渲染的文件，支持glob模式
  # - "*.txt"                        # 示例：跳过所有txt文件
  # - "admin/**"                     # 示例：跳过admin目录下所有文件

# ============================================
# 文章写作配置
# ============================================
new_post_name: :title.md             # 新文章文件名格式
default_layout: post                 # 默认布局 (post文章, page页面, draft草稿)
titlecase: false                     # 是否将标题转换为标题格式 (每个单词首字母大写)
external_link:                       # 外部链接处理
  enable: true                       # 是否启用外部链接处理
  field: site                        # 处理范围 (site整站, post仅文章)
  exclude: ''                        # 排除的域名，用逗号分隔
filename_case: 0                     # 文件名大小写 (0不变, 1小写, 2大写)
render_drafts: false                 # 是否渲染草稿文件
post_asset_folder: false             # 是否启用文章资源文件夹 (每篇文章一个同名文件夹)
relative_link: false                 # 是否将链接转换为相对地址
future: true                         # 是否显示未来日期的文章
highlight_theme: github              # 代码高亮主题
syntax_highlighter: highlight.js    # 语法高亮器 (highlight.js 或 prismjs)

# Highlight.js 配置
highlight:
  line_number: true                  # 是否显示行号
  auto_detect: false                 # 是否自动检测语言
  tab_replace: '    '                # 制表符替换，空字符串表示不替换
  wrap: true                         # 是否换行
  hljs: false                        # 是否使用hljs类名
  exclude_languages:                 # 排除的语言
    # - 'example'

# PrismJS 配置 (如果使用 prismjs 作为语法高亮器)
prismjs:
  preprocess: true                   # 是否预处理
  line_number: true                  # 是否显示行号
  tab_replace: '    '                # 制表符替换

# ============================================
# 首页设置
# ============================================
index_generator:
  path: ''                           # 首页路径，通常为空
  per_page: 10                       # 每页显示文章数量，0表示不分页
  order_by: -date                    # 文章排序方式 (-date按日期倒序, date按日期正序, -updated按更新时间倒序)

# ============================================
# 分类和标签配置
# ============================================
default_category: uncategorized      # 默认分类名称
category_map:                        # 分类名称映射，用于URL美化
  # "编程技术": "programming"
  # "生活随笔": "life"
tag_map:                             # 标签名称映射，用于URL美化
  # "JavaScript": "js"
  # "人工智能": "ai"

# ============================================
# 元数据配置
# ============================================
meta_generator: true                 # 是否在HTML中添加generator meta标签

# ============================================
# 日期和时间格式
# ============================================
# 使用 Moment.js 格式化日期时间
# 格式参考: http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD              # 日期格式 (YYYY年 MM月 DD日)
time_format: HH:mm:ss                # 时间格式 (HH小时 mm分钟 ss秒)
# 其他格式示例:
# date_format: YYYY年MM月DD日
# date_format: MMM DD, YYYY
# time_format: HH:mm

# 文章更新时间选项
updated_option: 'mtime'              # 更新时间来源 (mtime文件修改时间, date使用date字段, empty不显示)

# ============================================
# 分页配置
# ============================================
per_page: 10                         # 每页显示文章数量，0表示禁用分页
pagination_dir: page                 # 分页目录名称

# ============================================
# 文件包含/排除配置
# ============================================
# 注意：include/exclude 选项只对 source/ 文件夹有效
include:                             # 包含的文件，支持glob模式
  # - ".nojekyll"                    # 示例：包含.nojekyll文件
exclude:                             # 排除的文件，支持glob模式
  # - "*.tmp"                        # 示例：排除所有临时文件
  # - "drafts/**"                    # 示例：排除drafts目录
ignore:                              # 忽略的文件，支持glob模式
  # - "**/foo"                       # 示例：忽略所有名为foo的文件/目录

# ============================================
# 扩展配置
# ============================================
# 主题配置
theme: butterfly                     # 使用的主题名称

# 插件配置
plugins:                             # 启用的插件列表
  # - hexo-generator-feed            # RSS订阅插件
  # - hexo-generator-sitemap         # 站点地图插件
  # - hexo-generator-baidu-sitemap   # 百度站点地图插件
  # - hexo-deployer-git              # Git部署插件

# ============================================
# 部署配置
# ============================================
deploy:
  type: git                          # 部署类型 (git, ftp, rsync等)
  repository: git@github.com:cloak1522/418blog.git  # Git仓库地址
  branch: main                       # 部署分支
  # message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"  # 提交信息模板
  extend_dirs:                       # 扩展目录，用于清理旧文件
    - /                             # 清理根目录下的所有旧文件
  ignore_hidden: false               # 是否忽略隐藏文件
  ignore_pattern:                    # 忽略的文件模式
    public: .                        # 清理public目录下的所有文件
  # 强制完全清理并重新部署
  force: true                        # 强制推送，覆盖远程分支

# 多个部署目标示例:
# deploy:
#   - type: git
#     repository: git@github.com:username/username.github.io.git
#     branch: main
#   - type: git
#     repository: git@gitee.com:username/username.git
#     branch: master

# ============================================
# 服务器配置 (hexo server)
# ============================================
server:
  port: 4000                         # 本地服务器端口
  log: false                         # 是否显示访问日志
  ip: 0.0.0.0                        # 绑定IP地址，0.0.0.0表示所有接口
  compress: false                    # 是否启用gzip压缩
  header: true                       # 是否显示HTTP头信息

# ============================================
# 其他高级配置
# ============================================
# 模板引擎配置
template_engine: 'ejs'               # 模板引擎 (ejs, swig, nunjucks等)

# 文章摘要分隔符
excerpt_separator: '<!-- more -->'   # 文章摘要分隔符，在此之前的内容作为摘要

# 数据文件夹
data_dir: source/_data               # 数据文件目录，可存放YAML/JSON数据文件

# 主题配置文件
theme_config:                        # 主题配置，会覆盖主题默认配置
  # 在这里可以直接配置主题选项，无需修改主题文件
  # 示例：
  # menu:
  #   首页: /
  #   归档: /archives/
